export const LOAD_REPOSITORIES_FAILED = "LOAD_REPOSITORIES_FAILED";
export const LOAD_REPOSITORIES_STARTED = "LOAD_REPOSITORIES_STARTED";
export const LOAD_REPOSITORIES_FINISHED = "LOAD_REPOSITORIES_FINISHED";
