export const LOAD_REPOSITORIES_FAILED = "LOAD_REPOSITORIES_FAILED";
export const LOAD_REPOSITORIES_FINISHED = "LOAD_REPOSITORIES_FINISHED";

export const LOAD_COMMITS_FINISHED = "LOAD_COMMITS_FINISHED";
export const LOAD_COMMITS_FAILED = "LOAD_COMMITS_FAILED";

export const FILTER_COMMITS_FINISHED = "FILTER_COMMITS_FINISHED";
export const FILTER_COMMITS_FAILED = "FILTER_COMMITS_FAILED";
export const REMOVE_FILTER_FOR_COMMITS = "REMOVE_FILTER_FOR_COMMITS";
