export const LOAD_REPOSITORIES_FAILED = "LOAD_REPOSITORIES_FAILED";
export const LOAD_REPOSITORIES_FINISHED = "LOAD_REPOSITORIES_FINISHED";

export const LOAD_COMMITS_FINISHED = "LOAD_COMMITS_FINISHED";
export const LOAD_COMMITS_FAILED = "LOAD_COMMITS_FAILED";
